const shows = [
  {
    id: 1,
    title: "Breaking Bad",
    releaseDate: "20-1-2008",
    rating: 9.5,
    genre: ["Crime", "Drama", "Thriller"],
    image: "https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg",
  },
  {
    id: 2,
    title: "Game of Thrones",
    releaseDate: "17-4-2011",
    rating: 9.3,
    genre: ["Action", "Adventure", "Drama"],
    image: "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
  },
  {
    id: 3,
    title: "Stranger Things",
    releaseDate: "15-7-2016",
    rating: 8.7,
    genre: ["Drama", "Fantasy", "Horror"],
    image: "https://i.scdn.co/image/ab67616d0000b273bd0db295c0164ddbc0584ebb",
  },
  {
    id: 4,
    title: "The Mandalorian",
    releaseDate: "12-11-2019",
    rating: 8.8,
    genre: ["Action", "Adventure", "Fantasy"],
    image: "https://m.media-amazon.com/images/I/81oP0pVLi5L._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 5,
    title: "The Office",
    releaseDate: "24-3-2005",
    rating: 8.9,
    genre: ["Comedy"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg1M-IXxVnGM4EwNBhtTR8Z8DrOA_uqWPmew&s",
  },
  {
    id: 6,
    title: "Friends",
    releaseDate: "22-9-1994",
    rating: 8.9,
    genre: ["Comedy", "Romance"],
    image: "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
  },
  {
    id: 7,
    title: "The Witcher",
    releaseDate: "20-12-2019",
    rating: 8.2,
    genre: ["Action", "Adventure", "Drama"],
    image: "https://m.media-amazon.com/images/M/MV5BMDEwOWVlY2EtMWI0ZC00OWVmLWJmZGItYTk3YjYzN2Y0YmFkXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
  },
  {
    id: 8,
    title: "Sherlock",
    releaseDate: "25-7-2010",
    rating: 9.1,
    genre: ["Crime", "Drama", "Mystery"],
    image: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10406404_b_v13_ab.jpg",
  },
  {
    id: 9,
    title: "The Crown",
    releaseDate: "4-11-2016",
    rating: 8.6,
    genre: ["Biography", "Drama", "History"],
    image: "https://resizing.flixster.com/MbINOD-XxE4ZFDNDdzkLoKNsslc=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p14453812_b_v8_aa.jpg",
  },
  {
    id: 10,
    title: "Westworld",
    releaseDate: "2-10-2016",
    rating: 8.6,
    genre: ["Drama", "Mystery", "Sci-Fi"],
    image: "https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
  },
  {
    id: 11,
    title: "House of Cards",
    releaseDate: "1-2-2013",
    rating: 8.7,
    genre: ["Drama"],
    image: "https://m.media-amazon.com/images/M/MV5BNmM4ODU1MzItODYyYi00Y2U0LWFjZjItYTRhZWIwOGMyZTRhXkEyXkFqcGdeQXVyNjc2NTQ4Nzk@._V1_.jpg",
  },
  {
    id: 12,
    title: "The Boys",
    releaseDate: "26-7-2019",
    rating: 8.7,
    genre: ["Action", "Comedy", "Crime"],
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/14/The_Boys_Season_2.jpg/220px-The_Boys_Season_2.jpg",
  },
  {
    id: 13,
    title: "The Handmaid's Tale",
    releaseDate: "26-4-2017",
    rating: 8.4,
    genre: ["Drama", "Sci-Fi", "Thriller"],
    image: "https://m.media-amazon.com/images/M/MV5BN2M0NTdiMGYtNmFjZi00MjIxLWI3OTUtNTdmZDRlOTNiYWU0XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_.jpg",
  },
  {
    id: 14,
    title: "The Umbrella Academy",
    releaseDate: "15-2-2019",
    rating: 8.0,
    genre: ["Action", "Adventure", "Comedy"],
    image: "https://static0.srcdn.com/wordpress/wp-content/uploads/2024/02/the-umbrella-academy-season-4-poster-showing-five-walking.jpg",
  },
  {
    id: 15,
    title: "Black Mirror",
    releaseDate: "4-12-2011",
    rating: 8.8,
    genre: ["Drama", "Sci-Fi", "Thriller"],
    image: "https://m.media-amazon.com/images/M/MV5BZTgyNTBkNzctN2I3NC00NTA1LWJiMDMtYzA2MmYyZjc1NWQzXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
  },
  {
    id: 16,
    title: "The Walking Dead",
    releaseDate: "31-10-2010",
    rating: 8.2,
    genre: ["Drama", "Horror", "Thriller"],
    image: "https://m.media-amazon.com/images/M/MV5BNzI5MjUyYTEtMTljZC00NGI5LWFhNWYtYjY0ZTQ5YmEzMWRjXkEyXkFqcGdeQXVyMTY3MDE5MDY1._V1_.jpg",
  },
  {
    id: 17,
    title: "Narcos",
    releaseDate: "28-8-2015",
    rating: 8.8,
    genre: ["Biography", "Crime", "Drama"],
    image: "https://m.media-amazon.com/images/M/MV5BNmFjODU3YzgtMGUwNC00ZGI3LWFkZjQtMjkxZDc3NmQ1MzcyXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
  },
  {
    id: 18,
    title: "Better Call Saul",
    releaseDate: "8-2-2015",
    rating: 8.7,
    genre: ["Crime", "Drama"],
    image: "https://upload.wikimedia.org/wikipedia/en/c/c0/Better_Call_Saul_season_4.jpg",
  },
  {
    id: 19,
    title: "Peaky Blinders",
    releaseDate: "12-9-2013",
    rating: 8.8,
    genre: ["Crime", "Drama"],
    image: "https://rukminim2.flixcart.com/image/850/1000/k0y6cnk0/poster/9/f/6/medium-peaky-blinders-tv-series-poster-for-room-office-13-inch-x-original-imafkm3uhgwyy3gn.jpeg?q=20&crop=false",
  },
  {
    id: 20,
    title: "Ozark",
    releaseDate: "21-7-2017",
    rating: 8.4,
    genre: ["Crime", "Drama", "Thriller"],
    image: "https://resizing.flixster.com/3ko6zO6791p1QPOXHUI2eCwmHXQ=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvMDIyOTBmN2QtMzM0Yi00ODUxLWE0MWYtMmViYWJiOGViZjRkLmpwZw==",
  },
  {
    id: 21,
    title: "Vikings",
    releaseDate: "3-3-2013",
    rating: 8.5,
    genre: ["Action", "Adventure", "Drama"],
    image: "https://m.media-amazon.com/images/I/51ycz9p-jgL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 22,
    title: "Mindhunter",
    releaseDate: "13-10-2017",
    rating: 8.6,
    genre: ["Crime", "Drama", "Thriller"],
    image: "https://m.media-amazon.com/images/M/MV5BNWNmYzQ1ZWUtYTQ3ZS00Y2UwLTlkMDctZThlOTJkMGJiNzBiXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_.jpg",
  },
  {
    id: 23,
    title: "Chernobyl",
    releaseDate: "6-5-2019",
    rating: 9.4,
    genre: ["Drama", "History", "Thriller"],
    image: "https://m.media-amazon.com/images/M/MV5BNTdkN2QwMDItMDVhNS00ZjFiLWEzNTctMzY5ODQzYWNkMDllXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_FMjpg_UX1000_.jpg",
  },
  {
    id: 24,
    title: "Money Heist",
    releaseDate: "2-5-2017",
    rating: 8.3,
    genre: ["Action", "Crime", "Drama"],
    image: "https://m.media-amazon.com/images/M/MV5BODI0ZTljYTMtODQ1NC00NmI0LTk1YWUtN2FlNDM1MDExMDlhXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_FMjpg_UX1000_.jpg",
  },
  {
    id: 25,
    title: "Dark",
    releaseDate: "1-12-2017",
    rating: 8.8,
    genre: ["Crime", "Drama", "Mystery"],
    image: "https://resizing.flixster.com/lpJkDxnEFNQT1OWJjnmYfvpAHJ0=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjI2NjgyOS53ZWJw",
  },
  {
    id: 26,
    title: "The Marvelous Mrs. Maisel",
    releaseDate: "17-3-2017",
    rating: 8.7,
    genre: ["Comedy", "Drama"],
    image: "https://m.media-amazon.com/images/M/MV5BOWFjODRhMDktMTE3My00ODQzLThmODctYmM2ZmU5YmY0ZGVkXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg",
  },
  {
    id: 27,
    title: "Fargo",
    releaseDate: "15-4-2014",
    rating: 8.9,
    genre: ["Crime", "Drama", "Thriller"],
    image: "https://play-lh.googleusercontent.com/Qp_I7qT-23wjWzx5pML1RSA9gBQQIRU0iztrCi0DXdZRJEZupGoB_ur4TDDwgPa-pZ1c=w240-h480-rw",
  },
  {
    id: 28,
    title: "True Detective",
    releaseDate: "12-1-2014",
    rating: 8.9,
    genre: ["Crime", "Drama", "Mystery"],
    image: "https://m.media-amazon.com/images/M/MV5BNTEzMzBiNGYtYThiZS00MzBjLTk5ZWItM2FmMzU3Y2RjYTVlXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_FMjpg_UX1000_.jpg",
  },
  {
    id: 29,
    title: "The Queen's Gambit",
    releaseDate: "23-10-2020",
    rating: 8.6,
    genre: ["Drama"],
    image: "https://m.media-amazon.com/images/M/MV5BM2EwMmRhMmUtMzBmMS00ZDQ3LTg4OGEtNjlkODk3ZTMxMmJlXkEyXkFqcGdeQXVyMjM5ODk1NDU@._V1_FMjpg_UX1000_.jpg",
  }
];

export default shows;